### ISSUE TITLE
Crash when skipping stage 1

### ISSUE THREAD

**Issue by stelllaras** [hallamlab/SOFA#1]
When running SOFA without stage 1, the variable 'result' is undefined by the time it is checked at stage 2 (near line 545). A solution would be for function preProcess(options) to also return an error code like other steps.

One reason for skipping stage 1 would be to use a different tool for merging paired-end reads (e.g. PEAR).

Detailed error report:
Traceback (most recent call last):
  File "dependencies/SOFA/SOFA1.1.py", line 671, in <module>
    status, error = main(sys.argv[1:])
  File "dependencies/SOFA/SOFA1.1.py", line 545, in main
    if result[0]==0:
UnboundLocalError: local variable 'result' referenced before assignment

**Comment by ariahahn** [comment]
Hi,

Thanks for this. I will push a fix Monday to the github Monday and let you
know.

Aria

On Sat, Dec 12, 2015 at 2:48 PM, stelllaras notifications@github.com
wrote:

> When running SOFA without stage 1, the variable 'result' is undefined by
> the time it is checked at stage 2 (near line 545) A solution would be for
> function preProcess(options) to also return an error code like other steps
> 
> One reason for skipping stage 1 would be to use a different tool for
> merging paired-end reads (eg PEAR)
> 
> Detailed error report:
> Traceback (most recent call last):
> File "dependencies/SOFA/SOFA11py", line 671, in
> status, error = main(sysargv[1:])
> File "dependencies/SOFA/SOFA11py", line 545, in main
> if result[0]==0:
> UnboundLocalError: local variable 'result' referenced before assignment
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hallamlab/SOFA/issues/1.

## 

Aria Hahn MSc
PhD Candidate
www.cupcakesandscience.com
Hallam Laboratory
http://www.cmde.science.ubc.ca/hallam/index.php

University of British Columbia
Department of Microbiology & Immunology
Life Sciences Centre
2350 Health Sciences Mall (Rm 2520)
Vancouver, BC Canada V6T 1Z3
T: 604-827-4216
F: 604-822-6041
ariahahn@interchange.ubc.ca
