### ISSUE TITLE
FragGeneScanPlus version provided with SOFA misbehaves

### ISSUE THREAD

**Issue by stelllaras** [hallamlab/SOFA#3]
For some reason the output of the FGS+ provided with SOFA can produce a corrupted fasta file (stage3/<sample_name>.faa). For example:

> RAPTEIYPFSLPAPLPICRKSTRLNSSHVCSSD
> MGYLSDEERETLAPAEDLPHRFPIPTQIVSSDE
> B1_48053_2_1_101_+
> LGDRLAKLQGLSRRLFFQTAAGMAAAFVAMNQV
> PGLEPVDAGGEIPVQRRRPFCLPLRGCLLELL

As a result, LAST fails (throws a 'bad symbol' error).
However, SOFA1.1.py fails to detect the failure of LAST, because it does not check the return code of _execute_LAST(..). Hence, one obtains a final output (stage4/B1.SOFA.final.faa) that is also broken (e.g. which crashes MetaPathways). 

When using the original FGS+ the 1st problem is solved (although the problem of not correctly detecting LAST failures by SOFA remains).

**Comment by ariahahn** [comment]
This will be fixed in Monday's push. Thanks.

On Sunday, 13 December 2015, stelllaras notifications@github.com wrote:

> For some reason the output of the FGS+ provided with SOFA can produce a
> corrupted fasta file (stage3/faa) For example:
> 
> RAPTEIYPFSLPAPLPICRKSTRLNSSHVCSSD
> MGYLSDEERETLAPAEDLPHRFPIPTQIVSSDE
> B1_48053_2_1_101_+
> LGDRLAKLQGLSRRLFFQTAAGMAAAFVAMNQV
> PGLEPVDAGGEIPVQRRRPFCLPLRGCLLELL
> 
> As a result, LAST fails (throws a 'bad symbol' error)
> However, SOFA11py fails to detect the failure of LAST, because it does not
> check the return code of _execute_LAST() Hence, one obtains a final output
> (stage4/B1SOFAfinalfaa) that is also broken (eg which crashes MetaPathways)
> 
> When using the original FGS+ the 1st problem is solved (although the
> problem of not correctly detecting LAST failures by SOFA remains)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hallamlab/SOFA/issues/3.

## 

Aria Hahn MSc
PhD Candidate
www.cupcakesandscience.com
Hallam Laboratory
http://www.cmde.science.ubc.ca/hallam/index.php

University of British Columbia
Department of Microbiology & Immunology
Life Sciences Centre
2350 Health Sciences Mall (Rm 2520)
Vancouver, BC Canada V6T 1Z3
T: 604-827-4216
F: 604-822-6041
ariahahn@interchange.ubc.ca

**Comment by ariahahn** [comment]
These bugs have been fixed and pushed.

Thanks

On Sun, Dec 13, 2015 at 8:50 PM, Aria Hahn hahnaria@gmail.com wrote:

> This will be fixed in Monday's push. Thanks.
> 
> On Sunday, 13 December 2015, stelllaras notifications@github.com wrote:
> 
> > For some reason the output of the FGS+ provided with SOFA can produce a
> > corrupted fasta file (stage3/faa) For example:
> > 
> > RAPTEIYPFSLPAPLPICRKSTRLNSSHVCSSD
> > MGYLSDEERETLAPAEDLPHRFPIPTQIVSSDE
> > B1_48053_2_1_101_+
> > LGDRLAKLQGLSRRLFFQTAAGMAAAFVAMNQV
> > PGLEPVDAGGEIPVQRRRPFCLPLRGCLLELL
> > 
> > As a result, LAST fails (throws a 'bad symbol' error)
> > However, SOFA11py fails to detect the failure of LAST, because it does
> > not check the return code of _execute_LAST() Hence, one obtains a final
> > output (stage4/B1SOFAfinalfaa) that is also broken (eg which crashes
> > MetaPathways)
> > 
> > When using the original FGS+ the 1st problem is solved (although the
> > problem of not correctly detecting LAST failures by SOFA remains)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/hallamlab/SOFA/issues/3.
> 
> ## 
> 
> Aria Hahn MSc
> PhD Candidate
> www.cupcakesandscience.com
> Hallam Laboratory
> http://www.cmde.science.ubc.ca/hallam/index.php
> 
> University of British Columbia
> Department of Microbiology & Immunology
> Life Sciences Centre
> 2350 Health Sciences Mall (Rm 2520)
> Vancouver, BC Canada V6T 1Z3
> T: 604-827-4216
> F: 604-822-6041
> ariahahn@interchange.ubc.ca

## 

Aria Hahn MSc
PhD Candidate
www.cupcakesandscience.com
Hallam Laboratory
http://www.cmde.science.ubc.ca/hallam/index.php

University of British Columbia
Department of Microbiology & Immunology
Life Sciences Centre
2350 Health Sciences Mall (Rm 2520)
Vancouver, BC Canada V6T 1Z3
T: 604-827-4216
F: 604-822-6041
ariahahn@interchange.ubc.ca
